### ISSUE TITLE
MauiMoneyMate: Line break in labels not working

### ISSUE THREAD

**Issue by ArizonaGreenTea05** [ArizonaGreenTea05/FinancialOverview#46]
Line break works perfectly fine on load but is not responsive, even though the label height is responsive to how many lines the label should have
![image](https://github.com/ArizonaGreenTea05/FinancialOverview/assets/84347307/54d2f538-88bb-4e9b-875d-224fa6c6b3ae)
![image](https://github.com/ArizonaGreenTea05/FinancialOverview/assets/84347307/63548a7b-9c6a-4450-9faa-c52ef1a78170)

**Comment by ArizonaGreenTea05** [comment]
This is a known issue and has not been fixed yet. https://github.com/dotnet/maui/issues/10494

**Comment by ArizonaGreenTea05** [comment]
## Workaround
reload of the labels fixes it -> add reload when resizing has finished

**Comment by samhouts** [comment]
Duplicate of #10171
